drop table if exists user CASCADE ;

create table user (
	id bigint generated by default as identity,
	user_id varchar(255) not null,
	user_name varchar(255) not null,
	password varchar(255) not null,
	role integer,
	status integer,
	primary key (id)
);